### PR TITLE
add: details about OTC Talk 2

### PR DESCRIPTION
**Pull request by tusharnankani**

### CODE REVIEW

**Comment by HarshKapadia2** [comment]
We should add `2.html` as well, @tusharnankani. We can put in the abstract and other details. Please leave the info we don't have blank or add some placeholder there.

**Comment by HarshKapadia2** [comment]
Also I think it would be better to link the e-mail article in `2.html`, under the 'Relevant Links' sub-heading.

**Comment by tusharnankani** [comment]
On it.

**Comment by tusharnankani** [comment]
Here we go:

image


image


Will add relevant links (if any), after the talk.

**Comment by tusharnankani** [comment]
Merging for now. [Tweet is out](https://twitter.com/OurTechComm/status/1625728164755566592).

**Comment by HarshKapadia2** [comment]
Please add the e-mail article link to the 'Relevant Links' section later, @tusharnankani . Thank you!

**Comment by tusharnankani** [comment]
I did. It is the last line^

**Comment by HarshKapadia2** [comment]
You haven't added it to the sub-section though. Please do that when you add the 'Relevant Links' sub-section later.

**Pull request merged**
