### PR TITLE
feat: add details of OTC Talks 1

### PR DESCRIPTION
**Pull request by tusharnankani**
Looks like: 

image

### CODE REVIEW

**Comment by tusharnankani** [comment]
Had to run prettier as well. 
Effectively, only index is changed.

**Review by SirusCodes — APPROVED** [review]

**Comment by HarshKapadia2** [comment]
> Had to run prettier as well.

Why don't you just install the Prettier extension on VS Code? It formats on save...

**Comment by tusharnankani** [comment]
I keep changing my work environment. 

Sometimes it is codespaces, for smaller changes github.dev. I am having PC issues, so having to install VS Code again and again. 

That's why trying to remove the dependency altogether. 


A linter or an Action like formatter on PRs/commits make sense.

**Comment by HarshKapadia2** [comment]
> Sometimes it is codespaces, for smaller changes github.dev.

Well you can sync your VS Code extensions with your VS Code profile and that should automatically sync up all your environments.

> A linter or an Action like formatter on PRs/commits make sense.

What if it makes changes that we don't want? @KartikSoneji can you please weigh in here?

**Comment by tusharnankani** [comment]
Merging for now, we can continue the discussion @KartikSoneji

**Comment by KartikSoneji** [comment]
> A linter or an Action like formatter on PRs/commits make sense.

The issue with that is it makes follow-up commits much tricker.
If you open a PR with bad formatting, it will be corrected the first time.
But what happens if you push more commits?
They will conflict with the formatted code.
Resolving that will be a nightmare.

**Pull request merged**
